[package]
name = "pop-launcher-plugins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blocking = "1.3.0"
colorsys = "0.6.7"
futures-lite = "1.12.0"
log = "0.4.17"
mpris = "2.0.0"
notmuch = "0.8.0"
pop-launcher = "1.1.0"
regex = "1.7.1"
serde_json = "1.0.93"
systemd-journal-logger = "0.7.0"
tokio = { version = "1.25.0", features = ["rt", "macros", "process"] }
